import { Component } from '@angular/core';
import { HeaderComponent } from '../../../layouts/header/header.component';
import { SidebarComponent } from '../../../layouts/sidebar/sidebar.component';
import { TableModule } from 'primeng/table';

@Component({
  selector: 'app-anomalias-tables',
  standalone: true,
  imports: [HeaderComponent, SidebarComponent, TableModule],
  templateUrl: './anomalias-tables.component.html',
  styleUrl: './anomalias-tables.component.css'
})
export class AnomaliasTablesComponent {

  statuses!: any[];

  loading: boolean = true;

  activityValues: number[] = [0, 100];


  Plataformas = [
    {
      id: '49',
      Sistema: 'N/A',
      idIdent: 'PTB0364',
      idSistema: 'HA00000000002175',
      nivelAuditoria: 'CMSH',
      noNoConformidad: 'CMSH-ABK-D-07/2023-09',
      plataforma: 'Abk-D Permanente',
      descripcion: 'Escalera para acceso al cuarto de control modulo 8 con corrosión severa y perdida de material (tercer nivel) Tercer nivel, escalera para acceso al cuarto de control módulo 8.',
      nivelRiesgo: 'II',
      fechaDeteccion: '5/28/2019',
      fechaAtencion: '1/1/2019',
      estadoPACP: 'En proceso de cierre',
      avance: '100%',
      responsable: 'Julio Cesar Javier de la Fuente',
      responsableEjecutor: 'Enrique Chávez Galán',
    }, {
      id: '49',
      Sistema: 'N/A',
      idIdent: 'PTB0364',
      idSistema: 'HA00000000002175',
      nivelAuditoria: 'CMSH',
      noNoConformidad: 'CMSH-ABK-D-07/2023-09',
      plataforma: 'Abk-D Permanente',
      descripcion: 'Escalera para acceso al cuarto de control modulo 8 con corrosión severa y perdida de material (tercer nivel) Tercer nivel, escalera para acceso al cuarto de control módulo 8.',
      nivelRiesgo: 'II',
      fechaDeteccion: '5/28/2019',
      fechaAtencion: '1/1/2019',
      estadoPACP: 'En proceso de cierre',
      avance: '100%',
      responsable: 'Julio Cesar Javier de la Fuente',
      responsableEjecutor: 'Enrique Chávez Galán',
    }, {
      id: '49',
      Sistema: 'N/A',
      idIdent: 'PTB0364',
      idSistema: 'HA00000000002175',
      nivelAuditoria: 'CMSH',
      noNoConformidad: 'CMSH-ABK-D-07/2023-09',
      plataforma: 'Abk-D Permanente',
      descripcion: 'Escalera para acceso al cuarto de control modulo 8 con corrosión severa y perdida de material (tercer nivel) Tercer nivel, escalera para acceso al cuarto de control módulo 8.',
      nivelRiesgo: 'II',
      fechaDeteccion: '5/28/2019',
      fechaAtencion: '1/1/2019',
      estadoPACP: 'En proceso de cierre',
      avance: '100%',
      responsable: 'Julio Cesar Javier de la Fuente',
      responsableEjecutor: 'Enrique Chávez Galán',
    }, {
      id: '49',
      Sistema: 'N/A',
      idIdent: 'PTB0364',
      idSistema: 'HA00000000002175',
      nivelAuditoria: 'CMSH',
      noNoConformidad: 'CMSH-ABK-D-07/2023-09',
      plataforma: 'Abk-D Permanente',
      descripcion: 'Escalera para acceso al cuarto de control modulo 8 con corrosión severa y perdida de material (tercer nivel) Tercer nivel, escalera para acceso al cuarto de control módulo 8.',
      nivelRiesgo: 'II',
      fechaDeteccion: '5/28/2019',
      fechaAtencion: '1/1/2019',
      estadoPACP: 'En proceso de cierre',
      avance: '100%',
      responsable: 'Julio Cesar Javier de la Fuente',
      responsableEjecutor: 'Enrique Chávez Galán',
    }, {
      id: '49',
      Sistema: 'N/A',
      idIdent: 'PTB0364',
      idSistema: 'H2A00000000002175',
      nivelAuditoria: 'CMSH',
      noNoConformidad: 'CMSH-ABK-D-07/2023-09',
      plataforma: 'Abk-D Permanente',
      descripcion: 'Escalera para acceso al cuarto de control modulo 8 con corrosión severa y perdida de material (tercer nivel) Tercer nivel, escalera para acceso al cuarto de control módulo 8.',
      nivelRiesgo: 'II',
      fechaDeteccion: '5/28/2019',
      fechaAtencion: '1/1/2019',
      estadoPACP: 'En proceso de cierre',
      avance: '100%',
      responsable: 'Julio Cesar Javier de la Fuente',
      responsableEjecutor: 'Enrique Chávez Galán',
    }, {
      id: '49',
      Sistema: 'N/A',
      idIdent: 'PTB0364',
      idSistema: 'HA00000000002175',
      nivelAuditoria: 'CMSH',
      noNoConformidad: 'CMSH-ABK-D-07/2023-09',
      plataforma: 'Abk-D Permanente',
      descripcion: 'Escalera para acceso al cuarto de control modulo 8 con corrosión severa y perdida de material (tercer nivel) Tercer nivel, escalera para acceso al cuarto de control módulo 8.',
      nivelRiesgo: 'II',
      fechaDeteccion: '5/28/2019',
      fechaAtencion: '1/1/2019',
      estadoPACP: 'En proceso de cierre',
      avance: '100%',
      responsable: 'Julio Cesar Javier de la Fuente',
      responsableEjecutor: 'Enrique Chávez Galán',
    }, {
      id: '49',
      Sistema: 'N/A',
      idIdent: 'PTB0364',
      idSistema: 'HA00000000002175',
      nivelAuditoria: 'CMSH',
      noNoConformidad: 'CMSH-ABK-D-07/2023-09',
      plataforma: 'Abk-D Permanente',
      descripcion: 'Escalera para acceso al cuarto de control modulo 8 con corrosión severa y perdida de material (tercer nivel) Tercer nivel, escalera para acceso al cuarto de control módulo 8.',
      nivelRiesgo: 'II',
      fechaDeteccion: '5/28/2019',
      fechaAtencion: '1/1/2019',
      estadoPACP: 'En proceso de cierre',
      avance: '100%',
      responsable: 'Julio Cesar Javier de la Fuente',
      responsableEjecutor: 'Enrique Chávez Galán',
    }, {
      id: '49',
      Sistema: 'N/A',
      idIdent: 'PTB0364',
      idSistema: 'HA00000000002175',
      nivelAuditoria: 'CMSH',
      noNoConformidad: 'CMSH-ABK-D-07/2023-09',
      plataforma: 'Abk-D Permanente',
      descripcion: 'Escalera para acceso al cuarto de control modulo 8 con corrosión severa y perdida de material (tercer nivel) Tercer nivel, escalera para acceso al cuarto de control módulo 8.',
      nivelRiesgo: 'II',
      fechaDeteccion: '5/28/2019',
      fechaAtencion: '1/1/2019',
      estadoPACP: 'En proceso de cierre',
      avance: '100%',
      responsable: 'Julio Cesar Javier de la Fuente',
      responsableEjecutor: 'Enrique Chávez Galán',
    }, {
      id: '49',
      Sistema: 'N/A',
      idIdent: 'PTB0364',
      idSistema: 'HA00000000002175',
      nivelAuditoria: 'CMSH',
      noNoConformidad: 'CMSH-ABK-D-07/2023-09',
      plataforma: 'Abk-D Permanente',
      descripcion: 'Escalera para acceso al cuarto de control modulo 8 con corrosión severa y perdida de material (tercer nivel) Tercer nivel, escalera para acceso al cuarto de control módulo 8.',
      nivelRiesgo: 'II',
      fechaDeteccion: '5/28/2019',
      fechaAtencion: '1/1/2019',
      estadoPACP: 'En proceso de cierre',
      avance: '100%',
      responsable: 'Julio Cesar Javier de la Fuente',
      responsableEjecutor: 'Enrique Chávez Galán',
    }, {
      id: '1',
      Sistema: 'A',
      idIdent: 'PTB0364',
      idSistema: 'HA00000000002175',
      nivelAuditoria: 'CMSH',
      noNoConformidad: 'CMSH-ABK-D-07/2023-09',
      plataforma: 'Abk-D Permanente',
      descripcion: 'Escalera para acceso al cuarto de control modulo 8 con corrosión severa y perdida de material (tercer nivel) Tercer nivel, escalera para acceso al cuarto de control módulo 8.',
      nivelRiesgo: 'II',
      fechaDeteccion: '5/28/2019',
      fechaAtencion: '1/1/2019',
      estadoPACP: 'En proceso de cierre',
      avance: '100%',
      responsable: 'Julio Cesar Javier de la Fuente',
      responsableEjecutor: 'Enrique Chávez Galán',
    }, {
      id: '1',
      Sistema: 'N/A',
      idIdent: 'PTB0364',
      idSistema: 'HA00000000002175',
      nivelAuditoria: 'CMSH',
      noNoConformidad: 'CMSH-ABK-D-07/2023-09',
      plataforma: 'Abk-D Permanente',
      descripcion: 'Escalera para acceso al cuarto de control modulo 8 con corrosión severa y perdida de material (tercer nivel) Tercer nivel, escalera para acceso al cuarto de control módulo 8.',
      nivelRiesgo: 'II',
      fechaDeteccion: '5/28/2019',
      fechaAtencion: '1/1/2019',
      estadoPACP: 'En proceso de cierre',
      avance: '100%',
      responsable: 'Julio Cesar Javier de la Fuente',
      responsableEjecutor: 'Enrique Chávez Galán',
    }, {
      id: '49',
      Sistema: 'N/A',
      idIdent: 'PTB0364',
      idSistema: 'HA00000000002175',
      nivelAuditoria: 'CMSH',
      noNoConformidad: 'CMSH-ABK-D-07/2023-09',
      plataforma: 'Abk-D Permanente',
      descripcion: 'Escalera para acceso al cuarto de control modulo 8 con corrosión severa y perdida de material (tercer nivel) Tercer nivel, escalera para acceso al cuarto de control módulo 8.',
      nivelRiesgo: 'II',
      fechaDeteccion: '5/28/2019',
      fechaAtencion: '1/1/2019',
      estadoPACP: 'En proceso de cierre',
      avance: '100%',
      responsable: 'Julio Cesar Javier de la Fuente',
      responsableEjecutor: 'Enrique Chávez Galán',
    },
  ];
}
